module:
  mounts:
    - source: blox
      target: layouts/partials/blox/community/
      includeFiles: '**.html'
    - source: blox
      target: assets/dist/community/blox/
      includeFiles: '**.css'
